name: Pre-commit Check

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  precommit:
    name: Run Pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run pre-commit
        run: |
          pre-commit run --all-files || true

      - name: Check if there are changes
        run: |
          git diff --quiet || echo "CHANGES_DETECTED=true" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "[Format] chore: apply pre-commit fixes"
          git push
